<a href="https://colab.research.google.com/github/JairGF05/condiciones_numpy/blob/main/condiciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#creacion de array
#Genera 10 datos entre 1 y 10
arr = np.linspace(1,10,10, dtype=np.int8)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [5]:
#Condición para saber que valores del arreglo son mayores a 5
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
#Se puede filtrar el array solo para aquellos que cumplen determinada condición
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [8]:
#Ahora valores mayores que 5 pero menores que 9
arr[(arr > 5 ) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [11]:
#Reemplazar todos los valores mayores a 5 por 99
arr[(arr > 5)] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [12]:
#que muestre solo donde los valores son 99
arr[arr == 99]

array([99, 99, 99, 99, 99], dtype=int8)